name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Clone niri repository
        run: |
          cd ..
          git clone https://github.com/YaLTeR/niri.git && cd niri && git checkout 15c52bfb4318f3b2452f511d5367b4bfe6335242

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libinput-dev libudev-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          toolchain: stable
          components: clippy

      - name: Build
        run: cargo build --locked --workspace --all-targets --all-features

      - name: Clippy
        run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --locked --workspace --all-targets --all-features
